[project]
name = "sinduk"
dynamic = ["version"]
description = "A secure, local-first secrets manager and team vault system."
readme = "README.md"
authors = [
    { name = "Mobarak Hosen Shakil", email = "mh.ice.iu@gmail.com" }
]
license = "MIT"
license-files = ["LICENSE"]

requires-python = ">=3.10"
dependencies = [
    "cryptography>=42.0.0",
    "click>=8.0.0",
    "requests>=2.28.0",
    "pyperclip>=1.8.0",
    "rich>=13.0.0",
    "flask>=3.0.0",
    "flask-socketio>=5.3.0",
    "paramiko>=3.0.0",
    "bcrypt>=4.0.0",
    "simple-websocket>=1.0.0",
]
keywords = ["cli", "secrets", "encryption", "password", "token", "clipboard", "security", "vault", "sinduk"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop",
    "Topic :: Security :: Cryptography",
    "Topic :: Utilities"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "black>=24.0.0",
    "flake8>=7.0.0",
    "mypy>=1.8.0",
    "bandit>=1.7.0",
    "build>=1.0.0",
    "twine>=5.0.0",
    "pip-audit>=2.7.0",
]

[project.urls]
Homepage = "https://github.com/imshakil/sinduk"
Issues = "https://github.com/imshakil/sinduk/issues"

[project.scripts]
sinduk = "sinduk.cli:cli"
pacli = "sinduk.cli:cli"

[build-system]
requires = ["setuptools>=61.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["sinduk*"]
exclude = ["ref*", "tests*", "docs*"]

[tool.setuptools.package-data]
sinduk = ["web/templates/*", "web/static/*"]

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "no-local-version"

[tool.mypy]
ignore_missing_imports = true
